application: aroundme-photos
version: 4
runtime: php55
api_version: 1


handlers:
- url: /
  script: index.php
- url: /([a-z-]+)/([a-z-]+)/?$
  script: index.php
- url: /([a-z-]+)/?$
  script: index.php

- url: /appcache.php
  script: appcache.php


- url: /css
  static_dir: css
  application_readable: true
- url: /js
  static_dir: js
  application_readable: true
- url: /img
  static_dir: img
  application_readable: true
- url: /f
  static_dir: f
  application_readable: true

- url: /(.*\.(css|js|xml|json|txt))$
  static_files: \1
  upload: /.*\.(css|js|xml|json|txt)$
  expiration: "1d"
  application_readable: true

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|woff2|svg))$
  static_files: \1
  upload: /.*\.(ico|jpg|jpeg|png|gif|woff|woff2|svg)$
  expiration: "30d"
  application_readable: true


- url: /.*
  script: 404.php

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?\.codekit$
- ^(.*/)?\.zip$
- ^(.*/)?\.md$