# application: aroundme-photos
# version: 5
runtime: php55
api_version: 1

default_expiration: "1d"

handlers:
- url: /
  script: index.php
  secure: always
- url: /([a-z-]+)/([a-z-]+)/?$
  script: index.php
  secure: always
- url: /([a-z-]+)/?$
  script: index.php
  secure: always

- url: /appcache.php
  script: appcache.php
  secure: always

- url: /css
  static_dir: css
  application_readable: true
- url: /js
  static_dir: js
  application_readable: true
- url: /img
  static_dir: img
  application_readable: true
- url: /f
  static_dir: f
  application_readable: true


- url: /favicon\.ico
  static_files: img/config/favicon.ico
  upload: img/config/favicon\.ico
  expiration: "30d"
  application_readable: true


- url: /apple-touch-icon\.png
  static_files: img/config/apple-touch-icon.png
  upload: img/config/apple-touch-icon\.png
  expiration: "30d"
  application_readable: true


- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /manifest\.json
  static_files: static/manifest.json
  upload: static/manifest\.json

- url: /sitemap\.xml
  static_files: static/sitemap.xml
  upload: static/sitemap\.xml

- url: /browserconfig\.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig\.xml





- url: /(.*\.(css|js))$
  static_files: \1
  upload: /.*\.(css|js)$
  expiration: "1d"
  application_readable: true

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|woff2|svg))$
  static_files: \1
  upload: /.*\.(ico|jpg|jpeg|png|gif|woff|woff2|svg)$
  expiration: "30d"
  application_readable: true


- url: /.*
  script: 404.php
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?\.codekit3$
- ^(.*/)?\.zip$
- ^(.*/)?\.md$
- ^(sass/.*)
- ^(webapp/.*)